### ISSUE TITLE
Schemas from supermodel not fetched

### ISSUE THREAD

**Issue by vstirbu** [vstirbu/vscode-supermodel-test#1]
Intellisense enabled by schemas hosted on **schemastore** working:

<img width="1262" alt="Screenshot 2019-10-09 at 9 08 56" src="https://user-images.githubusercontent.com/1288047/66456354-158b4500-ea76-11e9-98a6-b486121dad32.png">

Intellisense enabled by schemas hosted on **supermodel** not working:

<img width="1262" alt="Screenshot 2019-10-09 at 9 09 04" src="https://user-images.githubusercontent.com/1288047/66456410-3489d700-ea76-11e9-9441-38cb495b4e09.png">

The schemas are configured following the `vscode-yaml` convention in `.vscode/settings.json`.

Fetching the schemas using `curl` works without problems from both schemastore and supermodel.

**Comment by vstirbu** [comment]
Intellisense works when serving a local copy of the schema fetched from supermodel using [https-server](https://www.npmjs.com/package/http-server).

**Comment by zdne** [comment]
@vstirbu by 

> Intellisense works when serving a local copy of the schema fetched from supermodel using https-server.

You mean you install the models locally and then you serve them with https server on local host?

**Comment by zdne** [comment]
For the record:

## Supermodel
```
$ curl -I http://supermodel.io/starwars/async/Film
HTTP/1.1 200 OK
Server: Cowboy
Date: Wed, 09 Oct 2019 07:16:56 GMT
Connection: keep-alive
Content-Type: application/schema+json
Etag: W/"3931dbb7090e3e19feb32fc95433b5f8"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 375bd1a6-36a0-4544-a6a1-eef3b4de722c
X-Runtime: 0.007938
Vary: Accept, Origin
Content-Length: 716
Via: 1.1 vegur
```

## Schemastore
```
$ curl -I http://json.schemastore.org/package
HTTP/1.1 200 OK
Cache-Control: public,max-age=31536000
Content-Length: 16993
Content-Type: application/json; charset=utf-8
Last-Modified: Mon, 29 Jul 2019 15:08:15 GMT
Accept-Ranges: bytes
ETag: "26c030721f46d51:0"
Vary: Accept-Encoding, If-Modified-Since
Server: Microsoft-IIS/10.0
Content-Security-Policy: object-src 'none';
Arr-Disable-Session-Affinity: True
Access-Control-Allow-Origin: *
Date: Wed, 09 Oct 2019 07:16:48 GMT
```

**Comment by zdne** [comment]
@vstirbu from the above, the content-type is different – couldn't that be a problem ?

**Comment by zdne** [comment]
@vstirbu can you please do the same `curl -I` against your local http server?

**Comment by vstirbu** [comment]
Yes. I do this sequence:

```
curl http://supermodel.io/vstirbu/CompliancePal/SoupDecisions -o schema.json
http-server
```

**Comment by vstirbu** [comment]
## http-server

```
$ curl -I http://localhost:8080/schema.json
HTTP/1.1 200 OK
server: ecstatic-3.3.1
cache-control: max-age=3600
last-modified: Wed, 09 Oct 2019 07:21:44 GMT
etag: W/"22196136-714-2019-10-09T07:21:44.190Z"
content-length: 714
content-type: application/json; charset=UTF-8
Date: Wed, 09 Oct 2019 07:25:03 GMT
Connection: keep-alive
```

**Comment by zdne** [comment]
Thanks, so our suspicion now is the content-type. We are going to test it.

**Comment by vstirbu** [comment]
That might not be the reason. This one works too, with content-type `application/octet-stream`:

```
$ curl -I http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json
HTTP/1.1 200 OK
Content-Length: 200690
Content-Type: application/octet-stream
Content-MD5: YeDLf4kZn2rSc7eluUBvWg==
Last-Modified: Fri, 04 Oct 2019 23:42:45 GMT
ETag: 0x8D749248EA8E672
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 7b86d1ed-101e-00e8-4b74-7ef20b000000
x-ms-version: 2009-09-19
x-ms-lease-status: unlocked
x-ms-blob-type: BlockBlob
X-Powered-By: ARR/3.0
X-Powered-By: ASP.NET
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
Set-Cookie: ARRAffinity=20210de274494a85c9ada1de48b2c0b01ead37eaecf24ae926dc43abeaeb9e1a;Path=/;HttpOnly;Domain=schema.management.azure.com
Date: Wed, 09 Oct 2019 07:36:05 GMT
```

**Comment by zdne** [comment]
@vstirbu can you check now? we believe we have fixed the problem...

**Comment by vstirbu** [comment]
It is fixed. Thanks! 🚀

**Comment by zdne** [comment]
Amazing!
